### ISSUE TITLE
Running error: rating

### ISSUE THREAD

**Issue by NsCrosu** [Yan233th/Arcaea-Local-Best30-Computing#3]
Traceback (most recent call last):
  File "D:\App\Arcaea-Local-Best30-Computing-main\main.py", line 52, in <module>
    rating = result[0][0] / 10
IndexError: list index out of range

**Comment by Yan233th** [comment]
抱歉高三忙，没空看，能提供一下你的db数据库吗

**Comment by NsCrosu** [comment]
不好意思，由于时间久远，文件已经丢失了…您高考加油在 2023年10月1日，16:55，Yan233_ ***@***.***> 写道：﻿
抱歉高三忙，没空看，能提供一下你的db数据库吗
